polar_bear_terms = {
    "niedźwiedź polarny": "polar bear",
    "mały miś": "cub",
    "Arktyka": "Arctic",
    "śnieg": "snow",
    "lód": "ice",
    "góra lodowa": "iceberg",
    "zimno": "cold",
    "mróz": "frost",
    "wiatr": "wind",
    "zima": "winter",
    "biały": "white",
    "futro": "fur",
    "łapa": "paw",
    "pazury": "claws",
    "nos": "nose",
    "uszy": "ears",
    "oczy": "eyes",
    "ogon": "tail",
    "zęby": "teeth",
    "zwierzę": "animal",
    "dzikie zwierzę": "wild animal",
    "ssak": "mammal",
    "natura": "nature",
    "ocean": "ocean",
    "morze": "sea",
    "woda": "water",
    "pływać": "swim",
    "nurkować": "dive",
    "ryba": "fish",
    "foka": "seal",
    "polowanie": "hunting",
    "jeść": "eat",
    "spać": "sleep",
    "biegać": "run",
    "chodzić": "walk",
    "silny": "strong",
    "duży": "big",
    "mały": "small",
    "szybki": "fast",
    "niebezpieczny": "dangerous",
    "przyjazny": "friendly",
    "klimat": "climate",
    "globalne ocieplenie": "global warming",
    "topnienie lodu": "melting ice",
    "ochrona zwierząt": "animal protection",
    "zagrożony gatunek": "endangered species",
    "północ": "north",
    "biegun północny": "North Pole",
    "temperatura": "temperature",
    "noc": "night",
    "dzień": "day",
    "słońce": "sun",
    "księżyc": "moon",
    "gwiazdy": "stars",
    "niebo": "sky",
    "las": "forest",
    "skała": "rock",
    "śnieżyca": "snowstorm",
    "lodowiec": "glacier",
    "zimna woda": "cold water",
    "gruby": "fat",
    "głodny": "hungry",
    "samotny": "lonely",
    "rodzina": "family",
    "mama": "mother",
    "ojciec": "father",
    "dziecko": "baby",
    "podróż": "journey",
    "ślad": "track",
    "cisza": "silence",
    "ekosystem": "ecosystem",
    "ochrona klimatu": "climate protection",
    "naukowiec": "scientist",
    "badanie": "research",
    "zagrożenie": "danger",
    "przetrwanie": "survival",
    "arktyczny wiatr": "arctic wind",
    "pokrywa lodowa": "ice sheet",
    "zamrożony ocean": "frozen ocean",
    "gruba warstwa lodu": "thick ice layer"
}
random_fact = [
    "Skóra misiów polarnych jest czarna, mimo że futro wygląda na białe.",
    "Futro misiów polarnych jest przezroczyste i odbija światło.",
    "Misie polarne świetnie pływają i mogą przepłynąć setki kilometrów.",
    "Misie polarne mają bardzo dobry węch.",
    "Misie polarne żyją w Arktyce.",
    "Łapy misiów polarnych pomagają nie zapadać się w śniegu.",
    "Misie polarne są największymi drapieżnikami lądowymi.",
    "Misie polarne potrafią zamykać nozdrza podczas pływania.",
    "Misie polarne jedzą głównie foki.",
    "Misie polarne mają grubą warstwę tłuszczu chroniącą przed zimnem."
]