climate_terms = {
    "Globalne ocieplenie": "Global warming",
    "Zmiana klimatu": "Climate change",
    "Efekt cieplarniany": "Greenhouse effect",
    "Topnienie lodowców": "Melting of glaciers",
    "Wzrost poziomu mórz": "Sea level rise",
    "Ekstremalne zjawiska pogodowe": "Extreme weather events",
    "Susza": "Drought",
    "Gazy cieplarniane": "Greenhouse gases",
    "Dwutlenek węgla": "Carbon dioxide",
    "Paliwa kopalne": "Fossil fuels",
    "Emisja spalin": "Exhaust emissions",
    "Deforestacja": "Deforestation",
    "Ślad węglowy": "Carbon footprint",
    "Odnawialne źródła energii": "Renewable energy sources",
    "Zrównoważony rozwój": "Sustainable development",
    "Efektywność energetyczna": "Energy efficiency",
    "Neutralność węglowa": "Carbon neutrality",
    "Ochrona środowiska": "Environmental protection",
    "Bioróżnorodność": "Biodiversity",
    "Recykling": "Recycling"
}